

export const reportData = [
    {
        id: 1,
        date: "2024-01-15",
        region: "North America",
        product: "Product A",
        revenue: 125000,
        forecast: "Linear Regression",
        accuracy: 94.2,
        variance: 5.8,
        status: "Completed",
    },
    {
        id: 2,
        date: "2024-01-15",
        region: "Europe",
        product: "Product B",
        revenue: 98000,
        forecast: "ARIMA",
        accuracy: 91.7,
        variance: 8.3,
        status: "Completed",
    },
    {
        id: 3,
        date: "2024-01-16",
        region: "Asia Pacific",
        product: "Product A",
        revenue: 156000,
        forecast: "Neural Network",
        accuracy: 96.1,
        variance: 3.9,
        status: "In Progress",
    },
    {
        id: 4,
        date: "2024-01-16",
        region: "North America",
        product: "Product C",
        revenue: 87500,
        forecast: "Linear Regression",
        accuracy: 89.4,
        variance: 10.6,
        status: "Completed",
    },
    {
        id: 5,
        date: "2024-01-17",
        region: "Europe",
        product: "Product A",
        revenue: 112000,
        forecast: "Random Forest",
        accuracy: 93.8,
        variance: 6.2,
        status: "Pending",
    },
    {
        id: 6,
        date: "2024-06-15",
        region: "North America",
        product: "Product F",
        revenue: 143000,
        forecast: "ARIMA",
        accuracy: 93.6,
        variance: 4.9,
        status: "Completed",
    },
    {
        id: 7,
        date: "2024-07-10",
        region: "Europe",
        product: "Product G",
        revenue: 101200,
        forecast: "Exponential Smoothing",
        accuracy: 90.1,
        variance: 6.7,
        status: "Pending",
    },
    {
        id: 8,
        date: "2024-08-08",
        region: "Asia",
        product: "Product H",
        revenue: 120000,
        forecast: "Random Forest",
        accuracy: 94.0,
        variance: 5.3,
        status: "Completed",
    },
    {
        id: 9,
        date: "2024-09-05",
        region: "South America",
        product: "Product I",
        revenue: 110500,
        forecast: "Linear Regression",
        accuracy: 88.8,
        variance: 7.2,
        status: "In Progress",
    },
    {
        id: 10,
        date: "2024-10-12",
        region: "Africa",
        product: "Product J",
        revenue: 95000,
        forecast: "ARIMA",
        accuracy: 89.5,
        variance: 6.8,
        status: "Completed",
    },
    {
        id: 11,
        date: "2024-11-15",
        region: "North America",
        product: "Product K",
        revenue: 127000,
        forecast: "Exponential Smoothing",
        accuracy: 92.7,
        variance: 5.1,
        status: "Completed",
    },
    {
        id: 12,
        date: "2024-12-01",
        region: "Europe",
        product: "Product L",
        revenue: 100000,
        forecast: "Random Forest",
        accuracy: 90.0,
        variance: 6.0,
        status: "Pending",
    },
    {
        id: 13,
        date: "2025-01-05",
        region: "Asia",
        product: "Product M",
        revenue: 118000,
        forecast: "Linear Regression",
        accuracy: 91.2,
        variance: 5.6,
        status: "Completed",
    },
    {
        id: 14,
        date: "2025-02-10",
        region: "South America",
        product: "Product N",
        revenue: 107500,
        forecast: "ARIMA",
        accuracy: 88.3,
        variance: 7.4,
        status: "In Progress",
    },
    {
        id: 15,
        date: "2025-03-18",
        region: "Africa",
        product: "Product O",
        revenue: 94000,
        forecast: "Exponential Smoothing",
        accuracy: 86.5,
        variance: 8.2,
        status: "Pending",
    },
    {
        id: 16,
        date: "2025-04-22",
        region: "North America",
        product: "Product P",
        revenue: 136500,
        forecast: "Random Forest",
        accuracy: 93.9,
        variance: 4.7,
        status: "Completed",
    },
    {
        id: 17,
        date: "2025-05-30",
        region: "Europe",
        product: "Product Q",
        revenue: 99000,
        forecast: "Linear Regression",
        accuracy: 89.1,
        variance: 6.6,
        status: "Completed",
    },
    {
        id: 18,
        date: "2025-06-10",
        region: "Asia",
        product: "Product R",
        revenue: 124000,
        forecast: "ARIMA",
        accuracy: 92.0,
        variance: 5.2,
        status: "In Progress",
    },
    {
        id: 19,
        date: "2025-07-14",
        region: "South America",
        product: "Product S",
        revenue: 115500,
        forecast: "Exponential Smoothing",
        accuracy: 90.6,
        variance: 6.4,
        status: "Completed",
    },
    {
        id: 20,
        date: "2025-08-01",
        region: "Africa",
        product: "Product T",
        revenue: 89000,
        forecast: "Random Forest",
        accuracy: 87.8,
        variance: 7.6,
        status: "Pending",
    },
    {
        id: 21,
        date: "2025-08-05",
        region: "North America",
        product: "Product U",
        revenue: 132000,
        forecast: "Linear Regression",
        accuracy: 91.8,
        variance: 5.4,
        status: "Completed",
    },
    {
        id: 22,
        date: "2025-08-07",
        region: "Europe",
        product: "Product V",
        revenue: 102500,
        forecast: "ARIMA",
        accuracy: 89.4,
        variance: 6.1,
        status: "Pending",
    },
    {
        id: 23,
        date: "2025-08-10",
        region: "Asia",
        product: "Product W",
        revenue: 117000,
        forecast: "Exponential Smoothing",
        accuracy: 92.5,
        variance: 5.0,
        status: "Completed",
    },
    {
        id: 24,
        date: "2025-08-12",
        region: "South America",
        product: "Product X",
        revenue: 111000,
        forecast: "Random Forest",
        accuracy: 93.1,
        variance: 4.8,
        status: "Completed",
    },
    {
        id: 25,
        date: "2025-08-14",
        region: "Africa",
        product: "Product Y",
        revenue: 88000,
        forecast: "Linear Regression",
        accuracy: 86.7,
        variance: 7.9,
        status: "In Progress",
    },
    {
        id: 26,
        date: "2025-08-15",
        region: "North America",
        product: "Product Z",
        revenue: 145000,
        forecast: "ARIMA",
        accuracy: 94.6,
        variance: 4.3,
        status: "Completed",
    },
    {
        id: 27,
        date: "2025-08-16",
        region: "Europe",
        product: "Product AA",
        revenue: 99000,
        forecast: "Exponential Smoothing",
        accuracy: 88.2,
        variance: 6.9,
        status: "Pending",
    },
    {
        id: 28,
        date: "2025-08-17",
        region: "Asia",
        product: "Product AB",
        revenue: 119000,
        forecast: "Random Forest",
        accuracy: 91.3,
        variance: 5.7,
        status: "Completed",
    },
    {
        id: 29,
        date: "2025-08-18",
        region: "South America",
        product: "Product AC",
        revenue: 113500,
        forecast: "Linear Regression",
        accuracy: 90.2,
        variance: 6.2,
        status: "Completed",
    },
    {
        id: 30,
        date: "2025-08-19",
        region: "Africa",
        product: "Product AD",
        revenue: 92000,
        forecast: "ARIMA",
        accuracy: 87.5,
        variance: 7.3,
        status: "Pending",
    },
    {
        id: 31,
        date: "2025-08-20",
        region: "North America",
        product: "Product AE",
        revenue: 129500,
        forecast: "Exponential Smoothing",
        accuracy: 92.9,
        variance: 4.6,
        status: "Completed",
    },
    {
        id: 32,
        date: "2025-08-21",
        region: "Europe",
        product: "Product AF",
        revenue: 103000,
        forecast: "Random Forest",
        accuracy: 90.7,
        variance: 5.9,
        status: "In Progress",
    },
    {
        id: 33,
        date: "2025-08-22",
        region: "Asia",
        product: "Product AG",
        revenue: 123000,
        forecast: "Linear Regression",
        accuracy: 91.6,
        variance: 5.1,
        status: "Completed",
    },
    {
        id: 34,
        date: "2025-08-23",
        region: "South America",
        product: "Product AH",
        revenue: 109000,
        forecast: "ARIMA",
        accuracy: 89.0,
        variance: 6.5,
        status: "Pending",
    },
    {
        id: 35,
        date: "2025-08-24",
        region: "Africa",
        product: "Product AI",
        revenue: 94000,
        forecast: "Exponential Smoothing",
        accuracy: 88.6,
        variance: 6.6,
        status: "Completed",
    },
    {
        id: 36,
        date: "2025-08-25",
        region: "North America",
        product: "Product AJ",
        revenue: 138000,
        forecast: "Random Forest",
        accuracy: 94.4,
        variance: 4.5,
        status: "Completed",
    },
    {
        id: 37,
        date: "2025-08-26",
        region: "Europe",
        product: "Product AK",
        revenue: 101500,
        forecast: "Linear Regression",
        accuracy: 90.4,
        variance: 5.8,
        status: "In Progress",
    },
    {
        id: 38,
        date: "2025-08-27",
        region: "Asia",
        product: "Product AL",
        revenue: 121500,
        forecast: "ARIMA",
        accuracy: 93.2,
        variance: 4.7,
        status: "Completed",
    },
    {
        id: 39,
        date: "2025-08-28",
        region: "South America",
        product: "Product AM",
        revenue: 114000,
        forecast: "Exponential Smoothing",
        accuracy: 91.0,
        variance: 5.3,
        status: "Completed",
    },
    {
        id: 40,
        date: "2025-08-29",
        region: "Africa",
        product: "Product AN",
        revenue: 90500,
        forecast: "Random Forest",
        accuracy: 86.9,
        variance: 7.7,
        status: "Pending",
    },
    {
        id: 41,
        date: "2025-08-30",
        region: "North America",
        product: "Product AO",
        revenue: 130000,
        forecast: "Linear Regression",
        accuracy: 91.1,
        variance: 5.2,
        status: "Completed",
    },
    {
        id: 42,
        date: "2025-08-31",
        region: "Europe",
        product: "Product AP",
        revenue: 104500,
        forecast: "ARIMA",
        accuracy: 89.7,
        variance: 6.0,
        status: "Pending",
    },
    {
        id: 43,
        date: "2025-09-01",
        region: "Asia",
        product: "Product AQ",
        revenue: 116000,
        forecast: "Exponential Smoothing",
        accuracy: 92.4,
        variance: 5.4,
        status: "Completed",
    },
    {
        id: 44,
        date: "2025-09-02",
        region: "South America",
        product: "Product AR",
        revenue: 110000,
        forecast: "Random Forest",
        accuracy: 93.0,
        variance: 4.6,
        status: "Completed",
    },
    {
        id: 45,
        date: "2025-09-03",
        region: "Africa",
        product: "Product AS",
        revenue: 89500,
        forecast: "Linear Regression",
        accuracy: 87.1,
        variance: 7.5,
        status: "In Progress",
    },
    {
        id: 46,
        date: "2025-09-04",
        region: "North America",
        product: "Product AT",
        revenue: 147000,
        forecast: "ARIMA",
        accuracy: 94.8,
        variance: 4.2,
        status: "Completed",
    },
    {
        id: 47,
        date: "2025-09-05",
        region: "Europe",
        product: "Product AU",
        revenue: 100500,
        forecast: "Exponential Smoothing",
        accuracy: 88.0,
        variance: 6.8,
        status: "Pending",
    },
    {
        id: 48,
        date: "2025-09-06",
        region: "Asia",
        product: "Product AV",
        revenue: 118500,
        forecast: "Random Forest",
        accuracy: 91.5,
        variance: 5.6,
        status: "Completed",
    },
    {
        id: 49,
        date: "2025-09-07",
        region: "South America",
        product: "Product AW",
        revenue: 112000,
        forecast: "Linear Regression",
        accuracy: 90.3,
        variance: 6.1,
        status: "Completed",
    },
    {
        id: 50,
        date: "2025-09-08",
        region: "Africa",
        product: "Product AX",
        revenue: 93500,
        forecast: "ARIMA",
        accuracy: 87.8,
        variance: 7.2,
        status: "Pending",
    },
    {
        id: 51,
        date: "2025-09-09",
        region: "North America",
        product: "Product AY",
        revenue: 131000,
        forecast: "Exponential Smoothing",
        accuracy: 92.6,
        variance: 4.7,
        status: "Completed",
    },
    {
        id: 52,
        date: "2025-09-10",
        region: "Europe",
        product: "Product AZ",
        revenue: 105000,
        forecast: "Random Forest",
        accuracy: 90.9,
        variance: 5.5,
        status: "In Progress",
    },
    {
        id: 53,
        date: "2025-09-11",
        region: "Asia",
        product: "Product BA",
        revenue: 122000,
        forecast: "Linear Regression",
        accuracy: 91.4,
        variance: 5.0,
        status: "Completed",
    },
    {
        id: 54,
        date: "2025-09-12",
        region: "South America",
        product: "Product BB",
        revenue: 108000,
        forecast: "ARIMA",
        accuracy: 89.1,
        variance: 6.3,
        status: "Pending",
    },
    {
        id: 55,
        date: "2025-09-13",
        region: "Africa",
        product: "Product BC",
        revenue: 95000,
        forecast: "Exponential Smoothing",
        accuracy: 88.4,
        variance: 6.5,
        status: "Completed",
    },
    {
        id: 56,
        date: "2025-09-14",
        region: "North America",
        product: "Product BD",
        revenue: 139000,
        forecast: "Random Forest",
        accuracy: 94.3,
        variance: 4.4,
        status: "Completed",
    },
    {
        id: 57,
        date: "2025-09-15",
        region: "Europe",
        product: "Product BE",
        revenue: 102000,
        forecast: "Linear Regression",
        accuracy: 90.2,
        variance: 5.6,
        status: "In Progress",
    },
    {
        id: 58,
        date: "2025-09-16",
        region: "Asia",
        product: "Product BF",
        revenue: 120000,
        forecast: "ARIMA",
        accuracy: 93.3,
        variance: 4.8,
        status: "Completed",
    },
    {
        id: 59,
        date: "2025-09-17",
        region: "South America",
        product: "Product BG",
        revenue: 115000,
        forecast: "Exponential Smoothing",
        accuracy: 91.1,
        variance: 5.2,
        status: "Completed",
    },
    {
        id: 60,
        date: "2025-09-18",
        region: "Africa",
        product: "Product BH",
        revenue: 91000,
        forecast: "Random Forest",
        accuracy: 86.8,
        variance: 7.4,
        status: "Pending",
    },
    {
        id: 61,
        date: "2025-09-19",
        region: "North America",
        product: "Product BI",
        revenue: 133000,
        forecast: "Linear Regression",
        accuracy: 91.9,
        variance: 5.3,
        status: "Completed",
    },
    {
        id: 62,
        date: "2025-09-20",
        region: "Europe",
        product: "Product BJ",
        revenue: 106500,
        forecast: "ARIMA",
        accuracy: 89.2,
        variance: 6.2,
        status: "Pending",
    },
    {
        id: 63,
        date: "2025-09-21",
        region: "Asia",
        product: "Product BK",
        revenue: 117500,
        forecast: "Exponential Smoothing",
        accuracy: 92.8,
        variance: 5.1,
        status: "Completed",
    },
    {
        id: 64,
        date: "2025-09-22",
        region: "South America",
        product: "Product BL",
        revenue: 111500,
        forecast: "Random Forest",
        accuracy: 93.4,
        variance: 4.9,
        status: "Completed",
    },
    {
        id: 65,
        date: "2025-09-23",
        region: "Africa",
        product: "Product BM",
        revenue: 88500,
        forecast: "Linear Regression",
        accuracy: 86.6,
        variance: 7.8,
        status: "In Progress",
    },
    {
        id: 66,
        date: "2025-09-24",
        region: "North America",
        product: "Product BN",
        revenue: 144500,
        forecast: "ARIMA",
        accuracy: 94.7,
        variance: 4.1,
        status: "Completed",
    },
    {
        id: 67,
        date: "2025-09-25",
        region: "Europe",
        product: "Product BO",
        revenue: 99000,
        forecast: "Exponential Smoothing",
        accuracy: 87.9,
        variance: 6.7,
        status: "Pending",
    },
    {
        id: 68,
        date: "2025-09-26",
        region: "Asia",
        product: "Product BP",
        revenue: 119500,
        forecast: "Random Forest",
        accuracy: 91.2,
        variance: 5.5,
        status: "Completed",
    },
    {
        id: 69,
        date: "2025-09-27",
        region: "South America",
        product: "Product BQ",
        revenue: 113000,
        forecast: "Linear Regression",
        accuracy: 90.0,
        variance: 6.0,
        status: "Completed",
    },
    {
        id: 70,
        date: "2025-09-28",
        region: "Africa",
        product: "Product BR",
        revenue: 92500,
        forecast: "ARIMA",
        accuracy: 87.6,
        variance: 7.1,
        status: "Pending",
    },
    {
        id: 71,
        date: "2025-09-29",
        region: "North America",
        product: "Product BS",
        revenue: 128000,
        forecast: "Exponential Smoothing",
        accuracy: 92.2,
        variance: 4.8,
        status: "Completed",
    },
    {
        id: 72,
        date: "2025-09-30",
        region: "Europe",
        product: "Product BT",
        revenue: 103500,
        forecast: "Random Forest",
        accuracy: 90.8,
        variance: 5.6,
        status: "In Progress",
    },
    {
        id: 73,
        date: "2025-10-01",
        region: "Asia",
        product: "Product BU",
        revenue: 124500,
        forecast: "Linear Regression",
        accuracy: 91.7,
        variance: 5.0,
        status: "Completed",
    },
    {
        id: 74,
        date: "2025-10-02",
        region: "South America",
        product: "Product BV",
        revenue: 109500,
        forecast: "ARIMA",
        accuracy: 88.9,
        variance: 6.4,
        status: "Pending",
    },
    {
        id: 75,
        date: "2025-10-03",
        region: "Africa",
        product: "Product BW",
        revenue: 94500,
        forecast: "Exponential Smoothing",
        accuracy: 88.5,
        variance: 6.6,
        status: "Completed",
    },
    {
        id: 76,
        date: "2025-10-04",
        region: "North America",
        product: "Product BX",
        revenue: 136000,
        forecast: "Random Forest",
        accuracy: 94.5,
        variance: 4.6,
        status: "Completed",
    },
    {
        id: 77,
        date: "2025-10-05",
        region: "Europe",
        product: "Product BY",
        revenue: 100000,
        forecast: "Linear Regression",
        accuracy: 90.5,
        variance: 5.7,
        status: "In Progress",
    },
    {
        id: 78,
        date: "2025-10-06",
        region: "Asia",
        product: "Product BZ",
        revenue: 122500,
        forecast: "ARIMA",
        accuracy: 93.1,
        variance: 4.7,
        status: "Completed",
    },
    {
        id: 79,
        date: "2025-10-07",
        region: "South America",
        product: "Product CA",
        revenue: 114500,
        forecast: "Exponential Smoothing",
        accuracy: 91.3,
        variance: 5.4,
        status: "Completed",
    },
    {
        id: 80,
        date: "2025-10-08",
        region: "Africa",
        product: "Product CB",
        revenue: 91500,
        forecast: "Random Forest",
        accuracy: 87.0,
        variance: 7.6,
        status: "Pending",
    },
    {
        id: 81,
        date: "2025-10-09",
        region: "North America",
        product: "Product CC",
        revenue: 134500,
        forecast: "Linear Regression",
        accuracy: 91.3,
        variance: 5.2,
        status: "Completed",
    },
    {
        id: 82,
        date: "2025-10-10",
        region: "Europe",
        product: "Product CD",
        revenue: 107000,
        forecast: "ARIMA",
        accuracy: 89.6,
        variance: 6.3,
        status: "Pending",
    },
    {
        id: 83,
        date: "2025-10-11",
        region: "Asia",
        product: "Product CE",
        revenue: 116500,
        forecast: "Exponential Smoothing",
        accuracy: 92.7,
        variance: 5.0,
        status: "Completed",
    },
    {
        id: 84,
        date: "2025-10-12",
        region: "South America",
        product: "Product CF",
        revenue: 110500,
        forecast: "Random Forest",
        accuracy: 93.5,
        variance: 4.5,
        status: "Completed",
    },
    {
        id: 85,
        date: "2025-10-13",
        region: "Africa",
        product: "Product CG",
        revenue: 88000,
        forecast: "Linear Regression",
        accuracy: 86.5,
        variance: 7.9,
        status: "In Progress",
    },
    {
        id: 86,
        date: "2025-10-14",
        region: "North America",
        product: "Product CH",
        revenue: 146000,
        forecast: "ARIMA",
        accuracy: 94.9,
        variance: 4.0,
        status: "Completed",
    },
    {
        id: 87,
        date: "2025-10-15",
        region: "Europe",
        product: "Product CI",
        revenue: 99500,
        forecast: "Exponential Smoothing",
        accuracy: 88.1,
        variance: 6.6,
        status: "Pending",
    },
    {
        id: 88,
        date: "2025-10-16",
        region: "Asia",
        product: "Product CJ",
        revenue: 120500,
        forecast: "Random Forest",
        accuracy: 91.4,
        variance: 5.4,
        status: "Completed",
    },
    {
        id: 89,
        date: "2025-10-17",
        region: "South America",
        product: "Product CK",
        revenue: 112500,
        forecast: "Linear Regression",
        accuracy: 90.1,
        variance: 6.2,
        status: "Completed",
    },
    {
        id: 90,
        date: "2025-10-18",
        region: "Africa",
        product: "Product CL",
        revenue: 93000,
        forecast: "ARIMA",
        accuracy: 87.7,
        variance: 7.3,
        status: "Pending",
    },
    {
        id: 91,
        date: "2025-10-19",
        region: "North America",
        product: "Product CM",
        revenue: 130500,
        forecast: "Exponential Smoothing",
        accuracy: 92.5,
        variance: 4.9,
        status: "Completed",
    },
    {
        id: 92,
        date: "2025-10-20",
        region: "Europe",
        product: "Product CN",
        revenue: 106000,
        forecast: "Random Forest",
        accuracy: 91.0,
        variance: 5.7,
        status: "In Progress",
    },
    {
        id: 93,
        date: "2025-10-21",
        region: "Asia",
        product: "Product CO",
        revenue: 123000,
        forecast: "Linear Regression",
        accuracy: 91.8,
        variance: 5.1,
        status: "Completed",
    },
    {
        id: 94,
        date: "2025-10-22",
        region: "South America",
        product: "Product CP",
        revenue: 108500,
        forecast: "ARIMA",
        accuracy: 89.3,
        variance: 6.5,
        status: "Pending",
    },
    {
        id: 95,
        date: "2025-10-23",
        region: "Africa",
        product: "Product CQ",
        revenue: 95500,
        forecast: "Exponential Smoothing",
        accuracy: 88.3,
        variance: 6.4,
        status: "Completed",
    },
    {
        id: 96,
        date: "2025-10-24",
        region: "North America",
        product: "Product CR",
        revenue: 140000,
        forecast: "Random Forest",
        accuracy: 94.2,
        variance: 4.3,
        status: "Completed",
    },
    {
        id: 97,
        date: "2025-10-25",
        region: "Europe",
        product: "Product CS",
        revenue: 101000,
        forecast: "Linear Regression",
        accuracy: 90.6,
        variance: 5.6,
        status: "In Progress",
    },
    {
        id: 98,
        date: "2025-10-26",
        region: "Asia",
        product: "Product CT",
        revenue: 121000,
        forecast: "ARIMA",
        accuracy: 93.0,
        variance: 4.6,
        status: "Completed",
    },
    {
        id: 99,
        date: "2025-10-27",
        region: "South America",
        product: "Product CU",
        revenue: 116000,
        forecast: "Exponential Smoothing",
        accuracy: 91.2,
        variance: 5.3,
        status: "Completed",
    },
    {
        id: 100,
        date: "2025-10-28",
        region: "Africa",
        product: "Product CV",
        revenue: 92000,
        forecast: "Random Forest",
        accuracy: 86.9,
        variance: 7.5,
        status: "Pending",
    },
]